### ISSUE TITLE
Get Panasonic CX350 to work with this module

### ISSUE THREAD

**Issue by TomEagle** [bitfocus/companion-module-panasonic-p2#11]
I have a CX350. I would like to use this module, but there seams to be problems. I would like to work with someone on this module.
Tom Eagle
dr.tom.eagle@gmail.com
816-524-4040 c

**Comment by TomEagle** [comment]
It appears to error out after 30 seconds or more with "Instance/Wrapper/Panasonic-P2: Wrong User". You can disable the connection and re-enable, then the error clear up for another 30 seconds or more. You can repeat this.

**Comment by premultiply** [comment]
Flawless support for CX350 is included in https://github.com/bitfocus/companion-module-panasonic-cameras

**Comment by TomEagle** [comment]
After a crash i get this in the log:

24.09.02 23:44:12 Instance/ModuleHost: Unhandled error restarting connection: Error: Restart forced
24.09.02 23:44:12 Instance/Wrapper/Panasonic-PTZ: Error from PTZ: HTTPError: Response code 404 (Not Found)
24.09.02 23:44:12 Instance/Wrapper/Panasonic-PTZ: Error from PTZ: HTTPError: Response code 404 (Not Found)
24.09.02 23:45:12 Instance/ModuleHost: Instance "Panasonic-PTZ" failed to init: Error: Cannot read properties of undefined (reading 'id') TypeError: Cannot read properties of undefined (reading 'id')
    at C:\Program Files\Companion\resources\bundled-modules\panasonic-ptz\main.js:2:425271
    at $t.init_actions (C:\Program Files\Companion\resources\bundled-modules\panasonic-ptz\main.js:2:433014)
    at $t.init (C:\Program Files\Companion\resources\bundled-modules\panasonic-ptz\main.js:2:385069)
    at C:\Program Files\Companion\resources\bundled-modules\panasonic-ptz\main.js:2:234458
    at C:\Program Files\Companion\resources\bundled-modules\panasonic-ptz\main.js:2:212297
    at t.default._tryToStartAnother (C:\Program Files\Companion\resources\bundled-modules\panasonic-ptz\main.js:2:211344)
    at C:\Program Files\Companion\resources\bundled-modules\panasonic-ptz\main.js:2:212504
    at new Promise (<anonymous>)
    at t.default.add (C:\Program Files\Companion\resources\bundled-modules\panasonic-ptz\main.js:2:212147)
    at $t._handleInit (C:\Program Files\Companion\resources\bundled-modules\panasonic-ptz\main.js:2:233989)
24.09.02 23:45:13 Instance/ModuleHost: Unhandled error restarting connection: Error: Restart forced
24.09.02 23:45:13 Instance/Wrapper/Panasonic-PTZ: Error from PTZ: HTTPError: Response code 404 (Not Found)

**Comment by TomEagle** [comment]
Is this a version you are talking about. Your module name has "cameras" while the one I get the above error has a module name of "camera" with version Help for Panasonic: PTZ Camera v2.4.0.

If I have the wrong module, please let me know how I can get your version.

Thanks, Tom Eagle

**Comment by premultiply** [comment]
You are using the wrong module.

Update Companion to a recent version and add a new device of type Panasonic Camera.

**Comment by TomEagle** [comment]
Where do I find the right module? I tried stable v3.3.1 and also Beta v3.4.0

If I have to install the module, are there instructions?

Thanks,
Tom Eagle

**Comment by TomEagle** [comment]
I found the correct modules in Beta (V3.4.0) and Experimental (V3.99),but
not is Stable (V3.3.1). Which version (Beta or Exp) should I use?

Do you have any instructions on how to set up the CX350 camera to work with
Companion-Module-Cameras?

I am getting there, slowly..
Thanks,
Tom Eagle (email ***@***.***>)
tel:816-524-4040 c
tel:816-524-4041 h
